# Generated by Django 3.1.1 on 2020-09-11 16:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('precinct_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('precinct_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('badge_number', models.CharField(max_length=100, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('race', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good_egg.force')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('officer_description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('formal_complaint', models.CharField(max_length=100, null=True)),
                ('formal_complaint_number', models.CharField(max_length=100, null=True)),
                ('witnesses_present', models.BooleanField(default=False)),
                ('witnesses_information', models.TextField(null=True)),
                ('private', models.BooleanField(default=False)),
                ('bad_apple', models.BooleanField(default=True)),
                ('officers', models.ManyToManyField(to='good_egg.Officer')),
            ],
        ),
    ]
