# Generated by Django 3.1.1 on 2020-09-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_egg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
