# Generated by Django 3.1.1 on 2020-09-12 22:34

from django.db import migrations, models
import good_egg.models


class Migration(migrations.Migration):

    dependencies = [
        ('good_egg', '0002_incident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(validators=[good_egg.models.date_must_be_past]),
        ),
        migrations.AlterField(
            model_name='officer',
            name='dob',
            field=models.DateField(null=True, validators=[good_egg.models.date_must_be_past]),
        ),
    ]
