# Generated by Django 3.1.1 on 2020-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_egg', '0003_auto_20200912_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='formal_complaint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='formal_complaint_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='witnesses_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
