# Generated by Django 3.1.1 on 2020-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_egg', '0004_auto_20200913_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='formal_complaint',
            field=models.BooleanField(default=False),
        ),
    ]
