# Generated by Django 3.1.1 on 2020-09-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_egg', '0004_auto_20200911_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
