# Generated by Django 3.1.1 on 2020-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_egg', '0005_auto_20200913_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='officers',
            field=models.ManyToManyField(blank=True, to='good_egg.Officer'),
        ),
    ]
