# Generated by Django 3.1.1 on 2020-09-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_egg', '0006_auto_20200913_1426'),
        ('good_egg', '0004_auto_20200913_0533'),
    ]

    operations = [
    ]
